version: "2.2"
services:
  db:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NEO4J_AUTH: none
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      # NEO4J_dbms_read__only: "true"
      # NEO4J_dbms_shell_read__only: "true"
      # Guide
      NEO4J_browser_post__connect__cmd: "config; play http://localhost:7474/guides/combattb_neodb.html"
      #  Tuning
      # NEO4J_dbms_memory_pagecache_size: 8G
      # NEO4J_dbms_memory_heap_initial__size: 4G
      # NEO4J_dbms_memory_heap_max__size: 4G
    volumes_from:
      - dc
    network_mode: "bridge"
    ports:
      - "7687:7687"
      - "7474:7474"
  dc:
    build: dc/
    network_mode: "bridge"
    
  es:
    restart: always
    build: esdata/
    network_mode: "bridge"
    ports:
    - "9200:9200"
